language: python
dist: trusty
branches:
  only:
  - travis

python:
  - 2.7
install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install -r requirements.txt
  - pip install -i https://pypi.anaconda.org/probcomp/simple cgpm
  - pip install -i https://pypi.anaconda.org/probcomp/simple crosscat
script: ./check.sh
after_success:
  - python setup.py sdist
  - python setup.py bdist
  #- test $TRAVIS_BRANCH = "travis" && conda install conda-build && conda install anaconda-client && bash conda/conda_upload.sh
  - conda install anaconda-client && anaconda -t $CONDA_UPLOAD_TOKEN upload -u $CONDA_USER -l test dist/*.tar.gz --force
